Repository shaikhsajid1111/twitter-scraper-selenium, pull requests merged in 2022-10, with the labels that each got.

#30 scrap topic
  .pre-commit-config.yaml
  README.md
  twitter_scraper_selenium/__init__.py
  twitter_scraper_selenium/topic.py
Labels: hacktoberfest-accepted

#31 V3.0.0
  README.md
  setup.py
  twitter_scraper_selenium/driver_initialization.py
  twitter_scraper_selenium/driver_utils.py
  twitter_scraper_selenium/element_finder.py
  twitter_scraper_selenium/keyword.py
  twitter_scraper_selenium/profile.py
  twitter_scraper_selenium/scraping_utilities.py
  twitter_scraper_selenium/topic.py
Labels: bug, enhancement, hacktoberfest-accepted

#32 fixed invalid JSON format
  twitter_scraper_selenium/keyword.py
  twitter_scraper_selenium/profile.py
  twitter_scraper_selenium/topic.py
Labels: bug, hacktoberfest-accepted

#35 Fix for setting profile through browser argument on firefox
  twitter_scraper_selenium/driver_initialization.py
Labels: hacktoberfest-accepted

#36 V3.0.1
  setup.py
  twitter_scraper_selenium/driver_initialization.py
  twitter_scraper_selenium/driver_utils.py
  twitter_scraper_selenium/element_finder.py
  twitter_scraper_selenium/keyword.py
  twitter_scraper_selenium/profile.py
  twitter_scraper_selenium/scraping_utilities.py
  twitter_scraper_selenium/topic.py
Labels: bug, enhancement, hacktoberfest-accepted

#39 V3.0.2
  setup.py
  twitter_scraper_selenium/driver_initialization.py
  twitter_scraper_selenium/driver_utils.py
  twitter_scraper_selenium/element_finder.py
  twitter_scraper_selenium/keyword.py
  twitter_scraper_selenium/profile.py
  twitter_scraper_selenium/scraping_utilities.py
Labels: bug, enhancement

#40 Fixes
  setup.py
  twitter_scraper_selenium/element_finder.py
Labels: bug

#41 V3.1.3
  README.md
  setup.py
  twitter_scraper_selenium/__init__.py
  twitter_scraper_selenium/element_finder.py
  twitter_scraper_selenium/keyword_api.py
  twitter_scraper_selenium/scraping_utilities.py
Labels: enhancement

#42 V3.2.3
  README.md
  setup.py
  twitter_scraper_selenium/__init__.py
  twitter_scraper_selenium/keyword_api.py
  twitter_scraper_selenium/profile_details.py
  twitter_scraper_selenium/scraping_utilities.py
Labels: enhancement

#44 Fixed Directory Issue
  setup.py
  twitter_scraper_selenium/keyword.py
  twitter_scraper_selenium/topic.py
Labels: bug

#45 V4.0.0
  README.md
  setup.py
  twitter_scraper_selenium/__init__.py
  twitter_scraper_selenium/element_finder.py
  twitter_scraper_selenium/keyword.py
  twitter_scraper_selenium/keyword_api.py
  twitter_scraper_selenium/profile.py
  twitter_scraper_selenium/scraping_utilities.py
  twitter_scraper_selenium/topic.py
  twitter_scraper_selenium/topic_api.py
Labels: enhancement
